export const APP_WRITE_ID = '6644c9200016a8acc5d7'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
